Convert everything to be an optional type
vapor-community/stripe-provider pull request #65
Opened 2018-09-14 03:10 UTC by anthonycastelli

There have been issues I guess with new accounts and weird values being returned by Stripe so it's safe to say that everything should just be an optional except for the absolute guarantee of non-optional values, aka stuff that has a concrete type and a returned value

- [ ] Balance
- [ ] Charges
- [ ] Connect
- [ ] Coupons
- [ ] Customers
- [ ] Disputes
- [ ] Ephemeral Keys (This one I don't think needs to be done since it does have concrete values from my understanding)
- [ ] Invoices
- [ ] Orders
- [ ] Other
- [ ] Payouts
- [ ] Plans
- [ ] Products
- [ ] Refunds
- [ ] SKU's
- [ ] Shipping
- [ ] Sources
- [ ] Subscriptions
- [ ] Tokens

If anyone has any input on this, feel free to comment.

2018-09-14 19:02 UTC, anthonycastelli commented
@Andrewangeta I got this all done. Take a look at it and if it looks good to you, lets merge it in, and then you can create anew branch for #66 based on this.

2018-09-14 21:23 UTC, Andrewangeta requested changes

2018-09-14 21:23 UTC, Andrewangeta commented on Sources/Stripe/Models/Connect/ExternalAccounts.swift
> +    public var totalCount: Int?
The init should replace `decode` with `decodeIfPresent` for optional values.
@anthonycastelli

2018-09-15 16:40 UTC, Andrewangeta approved these changes

2018-09-15 16:40 UTC, merged