Invoice properties
vapor-community/stripe-provider pull request #83
Opened 2018-11-23 14:50 UTC by baarde

This MR adds a few properties to `StripeInvoice`.

It also adds two types:

* `StripeInvoiceStatus`: This type is an enum of the statuses described in [the documentation](https://stripe.com/docs/api/invoices/object#invoice_object-status).
* `StripeBillingReason`: This type is not an enum but a raw-representable struct because we must be ready to accept unexpected values. In particular [the documentation](https://stripe.com/docs/api/invoices/object?lang=curl#invoice_object-billing_reason) does not mention `subscription_created`, which will become available when switching to [API version 2018-10-31](https://stripe.com/docs/upgrades#2018-10-31). Currently, there are no declarations for `subscription_created` (which is represented as `subscription_updated` for now) nor `subscription` (which appears only in old invoices) in order to avoid confusion.

2018-11-23 16:10 UTC, Andrewangeta requested changes

2018-11-23 16:10 UTC, Andrewangeta commented on Sources/Stripe/Models/Invoices/BillingReason.swift
> +public struct StripeBillingReason: RawRepresentable, Equatable, Codable {
This can actually be an enum.

2018-11-28 10:18 UTC, baarde commented on Sources/Stripe/Models/Invoices/BillingReason.swift
> +public struct StripeBillingReason: RawRepresentable, Equatable, Codable {
OK.

2018-12-06 13:39 UTC, baarde commented
Requested changes were made.

2018-12-23 18:07 UTC, anthonycastelli commented
@baarde Looks good to me.
@Andrewangeta Shall I merge this in?

2018-12-23 18:13 UTC, Andrewangeta commented
Yea sure thing

2018-12-23 18:31 UTC, anthonycastelli commented
@Andrewangeta You have to approve the changes since you originally requested it, won't let me approve it

2018-12-23 18:45 UTC, Andrewangeta approved these changes

2018-12-23 18:45 UTC, Andrewangeta commented on Sources/Stripe/Models/Invoices/BillingReason.swift
> +    case subscription       = "subscription"
Subscription doesn't need to have it's value set here. Also you can forgo the equal lining up of the `=` operator to be consistent with the rest of the codebase. Other than that it looks good to me 👍

2018-12-23 20:44 UTC, merged